/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        FizzBuzz fizzBuzz = new FizzBuzz();
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter a number: ");
        System.out.println(fizzBuzz.fizzBuzz(Integer.parseInt(scanner.nextLine())));
        scanner.close();
    }
}
